import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu, X, ArrowUpRight, Crosshair, MapPin, Phone, Mail, ChevronDown, Send, MessageCircle, Gamepad2, Radio} from 'lucide-react';
import {siteConfig, experiences, prices, faqs, arcadeGames, tvFeatures} from './data';
import './style.css';

const go = (id) => document.querySelector(id)?.scrollIntoView({behavior:'smooth'});
function Logo(){return <img className="logo" src="/images/logo/login-laser-tag.svg" alt="Login Laser Tag"/>}
function Header(){const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false); useEffect(()=>{const f=()=>setScrolled(scrollY>40);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]); const links=[['A ARENA','#arena'],['EXPERIÊNCIAS','#experiencias'],['PREÇOS','#precos'],['FAQ','#faq'],['CONTACTOS','#contactos']]; return <header className={scrolled?'scrolled':''}><a href="#top" aria-label="Página inicial"><Logo/></a><nav className={open?'open':''}>{links.map(([t,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{t}</a>)}<button className="nav-mobile-cta" onClick={()=>{go('#reservas');setOpen(false)}}>RESERVAR</button></nav><button className="menu" aria-label={open?'Fechar menu':'Abrir menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><button className="button header-cta" onClick={()=>go('#reservas')}>RESERVAR <ArrowUpRight/></button></header>}
function SectionTitle({eyebrow,title,text}){return <div className="section-title reveal"><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Booking(){const [sent,setSent]=useState(false);const submit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const d=new FormData(e.currentTarget);const m=`Olá! Gostaria de pedir uma reserva na Login Laser Tag.%0A%0AExperiência: ${d.get('tipo')}%0AData: ${d.get('data')} às ${d.get('hora')}%0AParticipantes: ${d.get('pessoas')}%0ANome: ${d.get('nome')}%0AEmail: ${d.get('email')}%0ATelefone: ${d.get('telefone')}%0APedidos: ${d.get('pedidos')||'—'}`;setSent(true);window.open(`https://wa.me/${siteConfig.whatsapp}?text=${m}`,'_blank','noopener');};return <section id="reservas" className="booking"><div className="booking-copy"><SectionTitle eyebrow="RESERVAS" title="PRONTO PARA JOGAR?" text="Envia o teu pedido. A disponibilidade é confirmada directamente pela equipa."/><div className="contact-lines"><a href={`tel:${siteConfig.phone.replace(/ /g,'')}`}><Phone/> {siteConfig.phone}</a><a href={`mailto:${siteConfig.email}`}><Mail/> {siteConfig.email}</a><a href="https://maps.google.com/?q=38.720668,-9.215943" target="_blank"><MapPin/> Carnaxide · Lisboa</a></div></div><form onSubmit={submit} className="form"> <div className="form-grid"><label>Data<input name="data" type="date" required/></label><label>Horário<select name="hora" required defaultValue=""><option value="" disabled>Selecciona</option><option>17:00</option><option>18:00</option><option>19:00</option><option>20:00</option><option>21:00</option></select></label><label>N.º de participantes<input name="pessoas" type="number" min="1" placeholder="Ex.: 10" required/></label><label>Tipo de experiência<select name="tipo" required defaultValue=""><option value="" disabled>Selecciona</option>{['Laser Tag','Festa de aniversário','Evento de empresa','Reunião de amigos','Despedida de solteiro/a','Reunião de família'].map(x=><option key={x}>{x}</option>)}</select></label><label>Nome<input name="nome" autoComplete="name" required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label className="full">Telefone<input name="telefone" type="tel" autoComplete="tel" required/></label><label className="full">Pedidos especiais<textarea name="pedidos" rows="3" placeholder="Conta-nos o que precisamos de saber."/></label></div><button className="button submit" type="submit">PEDIR RESERVA <Send/></button>{sent&&<p className="success">Pedido preparado. Abriu uma mensagem no WhatsApp para o enviares à equipa.</p>}</form></section>}
function App(){const [activeFaq,setActiveFaq]=useState(null);const [whats,setWhats]=useState(false);useEffect(()=>{const reveal=()=>{document.querySelectorAll('.reveal').forEach(x=>{if(x.getBoundingClientRect().top<innerHeight*.88)x.classList.add('shown')});setWhats(scrollY>500)};addEventListener('scroll',reveal);reveal();return()=>removeEventListener('scroll',reveal)},[]);return <><Header/><main id="top"><section className="hero"><img src="/images/arena/player-action.png" alt="Jogador em acção na arena Login Laser Tag"/><div className="hero-overlay"/><div className="hero-content"><p className="kicker"><span/> CARNAXIDE · LISBOA</p><h1>ENTRA<br/>NA <i>ARENA.</i></h1><p className="lead">Laser Tag, competição e adrenalina numa arena de 300 m².</p><div className="hero-actions"><button className="button" onClick={()=>go('#reservas')}>RESERVAR AGORA <ArrowUpRight/></button><button className="text-button" onClick={()=>go('#arena')}>CONHECER A ARENA <span>↓</span></button></div></div><div className="hero-stats"><div><b>6+</b><small>ANOS</small></div><div><b>20</b><small>JOGADORES</small></div><div><b>300</b><small>M² ARENA</small></div></div><div className="laser l1"/><div className="laser l2"/></section>
<section className="experience wrap"><SectionTitle eyebrow="A EXPERIÊNCIA" title="ISTO NÃO É SÓ UM JOGO." text="Estratégia wireless, sem tinta e sem dor. Só a tua equipa, a arena e a próxima jogada."/><div className="stat-grid reveal">{[['300','M²','ARENA'],['20','','JOGADORES'],['6+','','IDADE MÍNIMA'],['12','MIN','POR JOGO']].map(x=><div className="stat" key={x[2]}><strong>{x[0]}<em>{x[1]}</em></strong><span>{x[2]}</span></div>)}</div><div className="ticker"><span>ESTRATÉGIA · VELOCIDADE · PRECISÃO · EQUIPA · ESTRATÉGIA · VELOCIDADE · PRECISÃO · EQUIPA ·</span></div></section>
<section id="arena" className="arena"><div className="wrap"><SectionTitle eyebrow="O ESPAÇO" title="UMA ARENA. MIL POSSIBILIDADES." text="A maior arena de Laser Tag de Portugal e Espanha, dentro de um espaço de aproximadamente 1.000 m²."/><div className="mosaic reveal"><figure className="main-img"><img src="/images/arena/arena-blue.png" alt="Vista da arena iluminada com néon"/><figcaption>300 M² DE ARENA <Crosshair/></figcaption></figure><figure className="side-img"><img src="/images/cafe/cafe-bar.png" alt="Café e bar da Login Laser Tag"/><figcaption>CAFÉ / BAR</figcaption></figure><div className="arena-note"><span>ESPAÇO TOTAL</span><b>1.000 <i>M²</i></b><p>Arena · café/bar · esplanada · arcade · festas e eventos</p></div></div></div></section>
<section id="experiencias" className="wrap missions"><SectionTitle eyebrow="EXPERIÊNCIAS" title="ESCOLHE A TUA MISSÃO."/><div className="mission-grid">{experiences.map(([title,desc,img],i)=><article className="mission reveal" key={title}><img src={img} alt="" loading="lazy"/><div className="mission-copy"><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p><button onClick={()=>go('#reservas')}>PEDIR RESERVA <ArrowUpRight/></button></div></article>)}</div></section>
<section className="arcade"><div className="wrap arcade-layout"><div className="arcade-copy"><SectionTitle eyebrow="JOGOS ARCADE" title="A MISSÃO NÃO ACABA NA ARENA." text="Depois do Laser Tag, o espaço tem jogos Arcade para prolongar o desafio."/><div className="arcade-icon"><Gamepad2/></div></div><div className="game-list reveal">{arcadeGames.map((game,i)=><div key={game}><span>{String(i+1).padStart(2,'0')}</span><b>{game}</b></div>)}</div></div></section>
<section id="precos" className="prices"><div className="wrap"><SectionTitle eyebrow="PREÇOS" title="ESCOLHE COMO QUERES JOGAR." text="Valores divulgados pela Login Laser Tag. Confirma a tua reserva com a equipa."/><div className="price-grid">{prices.map((p,i)=><article className={'price-card reveal '+(i===2?'highlight':'')} key={p.name}><span>{p.name}</span><strong>{p.price}</strong><small>{p.sub}</small><ul>{p.lines.map(l=><li key={l}>{l}</li>)}</ul><button onClick={()=>go('#reservas')}>RESERVAR ESTA EXPERIÊNCIA <ArrowUpRight/></button></article>)}</div></div></section>
<section className="hud wrap reveal"><div><p>MISSION STATUS</p><h3>LOGIN LASER TAG</h3><span>CARNAXIDE / LISBOA</span></div><dl><div><dt>PLAYERS</dt><dd>06—20</dd></div><div><dt>ARENA</dt><dd>300 M²</dd></div><div><dt>AGE</dt><dd>6+</dd></div><div><dt>STATUS</dt><dd className="ready">READY</dd></div></dl></section>
<Booking/>
<section className="tv wrap"><SectionTitle eyebrow="LOGIN NA TV" title="A ARENA JÁ ENTROU EM DIRECTO." text="A Login Laser Tag já marcou presença em televisão. Vê os conteúdos que a equipa disponibiliza."/><div className="tv-grid">{tvFeatures.map((item,i)=><article className="tv-card reveal" key={item.channel+item.title}><div><Radio/><span>ON AIR · 0{i+1}</span></div><p>{item.channel}</p><h3>{item.title}</h3><small>{item.host}</small>{item.url?<a href={item.url} target="_blank" rel="noreferrer">VER VÍDEO <ArrowUpRight/></a>:<span className="archive">CONTEÚDO DE ARQUIVO</span>}</article>)}</div></section>
<section id="faq" className="faq wrap"><SectionTitle eyebrow="FAQ" title="ANTES DA MISSÃO."/><div className="faq-list">{faqs.map(([q,a],i)=><article className={activeFaq===i?'active':''} key={q}><button onClick={()=>setActiveFaq(activeFaq===i?null:i)} aria-expanded={activeFaq===i}>{q}<ChevronDown/></button><div><p>{a}</p></div></article>)}</div></section>
<section id="contactos" className="location"><div className="map"><iframe title="Mapa da Login Laser Tag" loading="lazy" src="https://www.google.com/maps?q=38.720668,-9.215943&z=16&output=embed"/></div><div className="location-copy"><span>LOCALIZAÇÃO</span><h2>ENCONTRA-<i>NOS.</i></h2><p>{siteConfig.address}<br/>{siteConfig.postal}</p><a className="button" target="_blank" href="https://maps.google.com/?q=38.720668,-9.215943">ABRIR NO GOOGLE MAPS <ArrowUpRight/></a></div></section></main><footer><Logo/><div><a href="#arena">Arena</a><a href="#experiencias">Experiências</a><a href="#precos">Preços</a><a href="#reservas">Reservas</a><a href="#faq">FAQ</a></div><p>{siteConfig.phone} · {siteConfig.mobile}<br/><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p><small>© {new Date().getFullYear()} LOGIN LASER TAG</small></footer>{whats&&<a className="whatsapp" href={`https://wa.me/${siteConfig.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de saber mais sobre as reservas da Login Laser Tag.')}`} target="_blank" aria-label="Falar por WhatsApp"><MessageCircle/><span>Falar connosco</span></a>}</>};createRoot(document.getElementById('root')).render(<App/>);
